/**
 * GPX Smart Diff - Exporter Module
 */

export function exportGPX(geojsonData, filename) {
    if (!geojsonData) return;

    // We use a simplified GPX generation for better control over segments
    let gpx = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="GPX-Smart-Diff" xmlns="http://www.topografix.com/GPX/1/1">
  <metadata>
    <name>${filename}</name>
    <desc>Generated by Adventure Tools - GPX Smart Diff</desc>
  </metadata>`;

    if (geojsonData.type === 'FeatureCollection') {
        geojsonData.features.forEach(feature => {
            if (feature.geometry.type === 'LineString') {
                gpx += `
  <trk>
    <name>${filename} Segment</name>
    <trkseg>`;
                feature.geometry.coordinates.forEach(coord => {
                    gpx += `
      <trkpt lat="${coord[1]}" lon="${coord[0]}"></trkpt>`;
                });
                gpx += `
    </trkseg>
  </trk>`;
            } else if (feature.geometry.type === 'Point') {
                // Waypoint export
                const props = feature.properties || {};
                gpx += `
  <wpt lat="${feature.geometry.coordinates[1]}" lon="${feature.geometry.coordinates[0]}">
    <name>${props.name || 'Point'}</name>
  </wpt>`;
            }
        });
    }

    gpx += `
</gpx>`;

    // Download Logic
    const blob = new Blob([gpx], { type: 'application/gpx+xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${filename}.gpx`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}
